Dev
G-K-R-git/PY200-German pull request #3
Opened 2021-02-13 07:34 UTC by G-K-R-git

2021-02-13 09:49 UTC, EnotYoyo requested changes

2021-02-13 09:49 UTC, EnotYoyo commented on setup.py
> +        if self._day < 10:
Форматированный вывод: return f"{self.day:02d}.{self.month:02d}.{self.year:04d}"

2021-02-13 09:49 UTC, EnotYoyo commented on setup.py
> +        if year % 100 == 0 and year % 400 != 0:
Проверить year на int надо еще

2021-02-13 09:49 UTC, EnotYoyo commented on setup.py
> +        if month == 2 and not self.is_leap_year(year):
return self.days_in_month[month-1][self.is_leap_year(year)]

2021-02-13 09:49 UTC, EnotYoyo commented on setup.py
> +        if day > self.get_max_day(month, year):
А проверку корректности месяца и года?)

2021-02-13 09:49 UTC, EnotYoyo commented on setup.py
> +            if mon == 1 and not self.is_leap_year(year):
Писал выше. Не забывайте - bool - это наследник int'а

2021-02-13 09:49 UTC, EnotYoyo commented on setup.py
> +        day_num1 = self.convert_to_days(self._day, self._month, self._year)
Хорошо бы еще проверить, что other - это действительно Date,а если нет, то ВЕРНУТЬ NotImplemented (специальная константа)

2021-02-13 09:49 UTC, EnotYoyo commented on setup.py
> +        result_date = self.__add__(other)
не вызывайте магические  методы напрямую, на то они и магические: result_date = self + other

2021-02-13 09:50 UTC, EnotYoyo commented on tests.py
> +        test_timedelta = TimeDelta(1, 1, 1)
Тут лучше не смешивать. Один тест - проверяка Date, второй TimeDelta.

2021-02-13 09:51 UTC, EnotYoyo commented on tests.py
> +        Date("1.1.1")
Вот это я убрал бы отсюда. Лучше делить тесты на "хорошие" и "плохие"

2021-02-13 10:08 UTC, EnotYoyo commented on tests.py
> +        self.assertEqual(test_date.__repr__(), f"Date({date}, {month}, {year})", "Should be 'Date(1, 1, 1)'")
вызывайте магические методы с помощью функций: repr(test_date)

2021-02-13 10:08 UTC, EnotYoyo commented on tests.py
> +        self.assertEqual(test_date.__str__(), "01.01.0001")
Аналогично

2021-02-13 10:08 UTC, EnotYoyo commented on tests.py
> +        self.assertEqual(test_date1.__sub__(test_date2), -398)
аналогично: test_date1 - test_date2

2021-02-25 21:02 UTC, EnotYoyo approved these changes
Отлично :)

2021-02-25 21:02 UTC, EnotYoyo commented on date/date.py
> +        self.days = days
Лучше конечно провалидировать, что тут числа :)

2021-02-25 21:02 UTC, EnotYoyo commented on date/date.py
> +            self._day = args[0]
можно так: self._day, self._month, self._year = args

2021-02-25 21:02 UTC, EnotYoyo commented on date/date.py
> +        if 1 <= value <= 31:
Это проверка тут лишняя. Дальше все равно вызывается is_valid_date

2021-02-25 21:02 UTC, EnotYoyo commented on date/date.py
> +        if 1 <= value <= 12:
Аналогично

2021-02-25 21:02 UTC, EnotYoyo commented on date/date.py
> +        if 1 <= value:
Аналогично

2021-02-25 21:02 UTC, EnotYoyo commented on date/date.py
> +    def convert_to_days(self, day: int, month: int, year: int) -> int:
зачем тут передавать значения, если их можно взять из self?

2021-02-25 21:02 UTC, EnotYoyo commented on date/date.py
> +            if mon == 1:
Можно вызвать функцию get_max_days

2021-02-25 21:02 UTC, EnotYoyo commented on date/date.py
> +    def __add__(self, other: TimeDelta) -> "Date":
Тяжело читать функцию. Добавляйте в такие функции больше пустых строчек, отделяйте ими какие-то логические блоки функции. Добавляйте комментарии. 

Представьте, что в этой функции ошибка и Вам нужно будет ее найти через пару недель (месяцев, лет). Вам будет тяжело понять, что тут происходит

2021-02-25 21:02 UTC, EnotYoyo commented on tests/test_date.py
> +def test_correct_str_date():
тест без assert'a - это плохой тест :)

2021-02-25 21:02 UTC, EnotYoyo commented on tests/test_date.py
> +def test_correct_str_date():
Не считая `with pytest.raises `, конечно

2021-02-25 21:02 UTC, EnotYoyo commented on tests/test_date.py
> +def test_leap():
Я бы все таки разделил это на два теста и вынес бы года в декоратор

2021-02-25 21:02 UTC, EnotYoyo commented on tests/test_date.py
> +    test_date1 = Date(11, 11, 1111)
на такие сложные функции лучше больше тестов делать. И опять же, не забывайте про декоратор mark

2021-02-25 21:02 UTC, EnotYoyo commented on tests/test_date.py
> +    test_date = Date(11, 11, 1111)
Отделяйте блоки кода пустыми строчками

2021-02-25 21:02 UTC, EnotYoyo commented on tests/test_unittest.py
> +    def test_is_instance(self):
Этот тест не несет в себе полезной нагрузки

2021-02-25 21:02 UTC, EnotYoyo commented on tests/test_unittest.py
> +        test_timedelta = TimeDelta(1, 1, 1)
как и этот

2021-02-25 21:02 UTC, EnotYoyo commented on tests/test_unittest.py
> +        for i in (-1, 1, 32):
Лучше писать проще тесты, а то кто будет тестировать сами тесты? :)

2021-02-25 22:33 UTC, G-K-R-git commented on tests/test_unittest.py
> +        for i in (-1, 1, 32):
да, накрутил лишнего, но вы посоветовали всё же писать пайтест, поэтому юниттест я забросил пока что

2021-03-03 19:23 UTC, EnotYoyo commented on date/date.py
> +        if not isinstance((days or months or years), int):
not all(isinstance(part, int) for part in (days, months, years)). А такой код не так работает, как Вы ожидаете

2021-03-03 19:28 UTC, EnotYoyo commented
Принято

2021-03-03 22:12 UTC, merged